// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWTAESkpxSh-u9X0LrI7siWaoVvScebs',
    appId: '1:992888540641:web:caf7226e3eb2d1c40ed6a0',
    messagingSenderId: '992888540641',
    projectId: 'todoapp-b17d8',
    authDomain: 'todoapp-b17d8.firebaseapp.com',
    storageBucket: 'todoapp-b17d8.appspot.com',
    measurementId: 'G-PRWMFM1PXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtB5H1s2cKj_-pFHsnuPhe4u0Ihr4Kseo',
    appId: '1:992888540641:android:7d69d850b4e588f90ed6a0',
    messagingSenderId: '992888540641',
    projectId: 'todoapp-b17d8',
    storageBucket: 'todoapp-b17d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0wgjlgs45JVp4cZRIWVbhGxbx4obrg0',
    appId: '1:992888540641:ios:e87022a47311ab860ed6a0',
    messagingSenderId: '992888540641',
    projectId: 'todoapp-b17d8',
    storageBucket: 'todoapp-b17d8.appspot.com',
    iosClientId: '992888540641-14o7kmkd3u0t6s575fvaj8er0jtohov4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
